In [32]:
# Load required library modules
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
### working with csv files

# reading a csv file into a dataframe
# Example: ex1.csv
# print file contents
%pycat ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [4]:
# using read_csv function
df = pd.read_csv('ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [6]:
# reading file without header
# Example: ex2.csv
%pycat ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [7]:
# default column names: 0 to nc-1
pd.read_csv('ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [8]:
# specify header names
pd.read_csv('ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [10]:
# skipping rows with unwanted data
# e.g. comments
# Example: ex4.csv
%pycat ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [11]:
pd.read_csv('ex4.csv', skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [12]:
# handling missing values
# deafult: marked by some sentinel value (e.g., NaN)
# Example: ex5.csv
%pycat ex5.csv

something,a,b,c,d,message
one, 1,2,3,4,NA
two, 5,6,,8,world
three,9,10,11,12,foo

In [13]:
pd.read_csv('ex5.csv')

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [14]:
# using na_values argument to change the marking
# e.g., marking meaningless values such as foo using sentinels
sentinels = {'message': [ 'foo' ]}

In [15]:
pd.read_csv('ex5.csv', na_values=sentinels)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [16]:
# reading only sample cases for large datasets

# first approach:
# configure compact display settings
pd.options.display.max_rows = 10

In [18]:
df1 = pd.read_csv('ex6.csv')

In [19]:
df1.shape

(10000, 5)

In [21]:
df1

           one       two     three      four key
0     0.496714 -0.138264  0.647689  1.523030   P
1    -0.234153 -0.234137  1.579213  0.767435   C
2    -0.469474  0.542560 -0.463418 -0.465730   F
3     0.241962 -1.913280 -1.724918 -0.562288   T
4    -1.012831  0.314247 -0.908024 -1.412304   D
...        ...       ...       ...       ...  ..
9995 -0.790590  0.492624 -0.063768 -0.241301   U
9996 -0.841880 -1.604054  1.631534 -0.288728   O
9997  2.710492  0.772791  1.829253  0.993487   T
9998  0.158516 -0.597658 -0.976840  1.119651   M
9999  0.265034  0.616501  0.814624  0.355974   G

[10000 rows x 5 columns]

In [22]:
# second approach
# using nrows argument to specify no. of rows
pd.read_csv('ex6.csv', nrows=5)

        one       two     three      four key
0  0.496714 -0.138264  0.647689  1.523030   P
1 -0.234153 -0.234137  1.579213  0.767435   C
2 -0.469474  0.542560 -0.463418 -0.465730   F
3  0.241962 -1.913280 -1.724918 -0.562288   T
4 -1.012831  0.314247 -0.908024 -1.412304   D

In [23]:
# third approach
# using chunksize argument to specify a chunk in terms of no. of rows
# a TextParser object is returned
tp = pd.read_csv('ex6.csv', chunksize=500)

In [24]:
tp

In [25]:
tp.get_chunk()

          one       two     three      four key
0    0.496714 -0.138264  0.647689  1.523030   P
1   -0.234153 -0.234137  1.579213  0.767435   C
2   -0.469474  0.542560 -0.463418 -0.465730   F
3    0.241962 -1.913280 -1.724918 -0.562288   T
4   -1.012831  0.314247 -0.908024 -1.412304   D
..        ...       ...       ...       ...  ..
495 -0.971657 -1.379618 -0.626717  0.862393   V
496  0.953125  0.513085  0.725096  0.516178   Z
497 -0.641482  0.431923  0.800410  0.754291   N
498  1.188913  0.708304  0.351448  1.070150   R
499 -0.026521 -0.881875 -0.163067 -0.744903   G

[500 rows x 5 columns]

In [26]:
# writing a dataframe into a csv file
# using to_csv method
df.to_csv('write1.csv')

In [27]:
%pycat write1.csv

,a,b,c,d,message
0,1,2,3,4,hello
1,5,6,7,8,world
2,9,10,11,12,foo

In [28]:
# using other delimiters
# writing to sys.stdout
import sys
df.to_csv(sys.stdout, sep='|')

|a|b|c|d|message
0|1|2|3|4|hello
1|5|6|7|8|world
2|9|10|11|12|foo

In [29]:
# changing the 'empty string' senitnel for missing value
df2 = pd.read_csv('ex5.csv')
df2

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [30]:
df2.to_csv(sys.stdout)

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [31]:
df2.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [32]:
### working with Microsoft Excel files

# reading an excel file into a dataframe

# reading multiple sheets in a file
# it is faster to use ExcelFile function
# an ExcelFile object is returned

In [36]:
ef = pd.ExcelFile('ex1.xlsx')

In [37]:
ef

In [38]:
# using read_excel function to create the dataframe
df3 = pd.read_excel(ef, 'Sheet1')

In [39]:
df3

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [40]:
# for one sheet, it might be convient to pass the file path to the read_excel function
df3 = pd.read_excel('ex1.xlsx', 'Sheet1')

In [41]:
df3

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [42]:
# writing a dataframe into an excel file
# using the ExcelWriter function (suitable for writing multiple sheets)
# an ExcelWriter object is returned
ew = pd.ExcelWriter('write2.xlsx')

In [43]:
ew

In [44]:
# using to_excel function to write the dataframe
df3.to_excel(ew, 'Sheet1')

C:\Users\bhavi\AppData\Local\Temp\ipykernel_8484\65959313.py:2: FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  df3.to_excel(ew, 'Sheet1')

In [47]:
# save the write2.xlsx file using save method
ew.save()# not worked in newer version
ew.close()

AttributeError: 'OpenpyxlWriter' object has no attribute 'save'

In [49]:
# avoid ExcelWriter for one sheet
# pass the file path to the to_excel function
df3.to_excel('write3.xlsx')

In [50]:
### working with Web APIs
# sites offer public APIs to provide data feeds via JSON or some other format

# using requests package (easy to use)
import requests

In [51]:
# Example: GitHub website
# e.g., last 30 GitHub issues for pandas posted on GitHub
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'

In [52]:
# using get function
# a response object is returned
resp = requests.get(url)

In [53]:
resp

In [54]:
# using json method
# to obatin a list of dicts having all the data on a GitHub issue page (except for the comments)
v1 = resp.json()

In [55]:
v1

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68700',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68700/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68700/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68700/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/68700',
  'id': 5444348550,
  'node_id': 'PR_kwDOAA0YD88AAAABDYq_dw',
  'number': 68700,
  'title': 'DEPR: warn on ambiguous .loc MultiIndex tuple expansion',
  'user': {'login': 'krithikashreeL',
   'id': 69192489,
   'node_id': 'MDQ6VXNlcjY5MTkyNDg5',
   'avatar_url': 'https://avatars.githubusercontent.com/u/69192489?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/krithikashreeL',
   'html_url': 'https://github.com/krithikashreeL',
   'followers_url': 'https://api.github.com/users/krithikashreeL/followers',
   'following_url': 'https://api.github.com/users/krithikashreeL/following{/other_user}',
   'gists_url': 'https://api.github.com/users/krithikashreeL/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/krithikashreeL/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/krithikashreeL/subscriptions',
   'organizations_url': 'https://api.github.com/users/krithikashreeL/orgs',
   'repos_url': 'https://api.github.com/users/krithikashreeL/repos',
   'events_url': 'https://api.github.com/users/krithikashreeL/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/krithikashreeL/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-09-14T02:09:52Z',
  'updated_at': '2026-09-14T02:09:52Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'CONTRIBUTOR',
  'issue_field_values': [],
  'type': None,
  'active_lock_reason': None,
  'draft': True,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/68700',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/68700',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/68700.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/68700.patch',
   'merged_at': None},
  'body': '## Summary\r\n\r\n`.loc` tuple keys are ambiguous whenever a `MultiIndex` has `nlevels == ndim` (the common case: a 2-level MultiIndex on a 2D DataFrame) — `df.loc[(a, b)]` could mean the MultiIndex row key `(a, b)`, or it could mean `(row=a, col=b)`. Setitem currently resolves this by trying the MultiIndex-key lookup first and silently falling back to the `(row, col)` reading whenever that lookup fails, even when the fallback *expands* the frame with a new row and/or column. This is the same root ambiguity behind #27248 and #19110, where that silent fallback does the "wrong" thing for identical syntax.\r\n\r\nThis PR implements the "medium term" step proposed in #65326: warn (`Pandas4Warning`) when a tuple `.loc` setitem key doesn\'t match any existing `MultiIndex` key and the `(row, col)` reading would expand the frame. The warning is scoped specifically to the expansion case — warning on every MultiIndex-lookup fallback would also fire on the ordinary, non-expanding `df.loc[existing_row, existing_col] = val` idiom, which should keep working silently.\r\n\r\n```python\r\nmi = pd.MultiIndex.from_tuples([(1, 2), (3, 4)])\r\ndf = pd.DataFrame([[10, 20], [30, 40]], index=mi, columns=[100, 200])\r\n\r\ndf.loc[(1, 100)] = [1, 2]  # (1, 100) isn\'t an existing MI key, and reading it\r\n                           # as (row=1, col=100) would add a new column 100 ->\r\n                           # now warns, since this is the ambiguous expansion case\r\n```\r\n\r\ncloses #65326\r\n\r\n- [x] closes #65326\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests)\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) — ruff/pre-commit weren\'t available to run in this environment; please run before submitting\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions\r\n- [x] Added an entry in the latest `doc/source/whatsnew/v3.1.0.rst`\r\n- [x] I have reviewed and followed all the [contribution guidelines](https://pandas.pydata.org/docs/dev/development/contributing.html)\r\n\r\n- [x] I used AI to develop this pull request. I prompted it to follow AGENTS.md, I have reviewed and understood every change. I used Claude Sonnet 5 (High) to investigate the root cause, implement the fix, and write/run the tests, and I reviewed and verified the result myself.\r\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68700/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68700/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68699',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68699/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68699/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68699/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/68699',
  'id': 5444157022,
  'node_id': 'PR_kwDOAA0YD88AAAABDYhilg',
  'number': 68699,
  'title': 'BUG: preserve dtype for empty DataFrame min/max axis=1',
  'user': {'login': 'Dmao233',
   'id': 164994318,
   'node_id': 'U_kgDOCdWdDg',
   'avatar_url': 'https://avatars.githubusercontent.com/u/164994318?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Dmao233',
   'html_url': 'https://github.com/Dmao233',
   'followers_url': 'https://api.github.com/users/Dmao233/followers',
   'following_url': 'https://api.github.com/users/Dmao233/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Dmao233/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Dmao233/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Dmao233/subscriptions',
   'organizations_url': 'https://api.github.com/users/Dmao233/orgs',
   'repos_url': 'https://api.github.com/users/Dmao233/repos',
   'events_url': 'https://api.github.com/users/Dmao233/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Dmao233/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2026-09-14T01:34:47Z',
  'updated_at': '2026-09-14T07:40:09Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'NONE',
  'issue_field_values': [],
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/68699',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/68699',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/68699.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/68699.patch',
   'merged_at': None},
  'body': '- [x] closes #32802\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\n- [x] I have reviewed and followed all the [contribution guidelines](https://pandas.pydata.org/docs/dev/development/contributing.html)\nCheck exactly one of the following, per the [automated contributions policy](https://pandas.pydata.org/docs/dev/development/contributing.html#automated-contributions-policy):\n\n- [ ] I did **not** use AI to develop this pull request.\n- [x] I used AI to develop this pull request. I prompted it to follow `AGENTS.md`, I have reviewed and understood every change, and I have described above how I used it and exactly which tool, model version, and effort setting — e.g. `claude opus 4.8 (xhigh)`, not just `claude`.\n\n`DataFrame.min` / `max` with `axis=1` already preserve dtype on an empty homogeneous datetime-like frame via `_reduce`. `DataFrame.agg("min"/"max", axis=1)` still transposed first, so a 0-row frame became 0 columns and the result fell back to `float64`.\n\nFor a 0-row frame and a string reducer, skip the transpose and call `apply_str()` so the existing `_reduce` path runs. Regression covers empty UTC datetime, naive datetime, and timedelta; whatsnew under Numeric.\n\nAI: Cursor cloud agent (default cloud model for this account). I reviewed the patch against #32802 and the empty-frame `_reduce` path before opening.',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68699/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68699/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68689',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68689/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68689/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68689/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/68689',
  'id': 5442783525,
  'node_id': 'PR_kwDOAA0YD88AAAABDXdLjQ',
  'number': 68689,
  'title': 'BUG: read_csv c engine ignored na_values on a converters column (GH#13302)',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None,
    'archived_at': None,
    'archived_by': None},
   {'id': 2822342,
    'node_id': 'MDU6TGFiZWwyODIyMzQy',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Missing-data',
    'name': 'Missing-data',
    'color': 'd7e102',
    'default': False,
    'description': 'np.nan, pd.NaT, pd.NA, dropna, isnull, interpolate',
    'archived_at': None,
    'archived_by': None},
   {'id': 47229171,
    'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV',
    'name': 'IO CSV',
    'color': '5319e7',
    'default': False,
    'description': 'read_csv, to_csv',
    'archived_at': None,
    'archived_by': None}],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-09-13T21:04:49Z',
  'updated_at': '2026-09-13T21:04:50Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'MEMBER',
  'issue_field_values': [],
  'type': None,
  'active_lock_reason': None,
  'draft': True,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/68689',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/68689',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/68689.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/68689.patch',
   'merged_at': None},
  'body': 'closes #13302\n\nWhen a column has a `converters` entry, the default `c` engine silently ignored `na_values` *and* the default NA strings for that column, where the `python` engine applies them: `_convert_column_data` returned from the converter branch before any NA handling ran. This matches them against the converter\'s output, as the `python` engine does.\n\nThe `converters` docstring for `read_csv`/`read_table` and the matching text in `io.rst` documented the old `c`-engine behavior as the spec ("`na_values` and `keep_default_na` have no effect on a column that has a converter"), so they are updated too. The sharpest user-visible change is that an empty field under `converters={"a": str}` now reads as `NaN` rather than `""` — which is what the `python` engine already returned.\n\nTwo deliberate limits, both left for separate PRs:\n\n- A converter that *raises* on the NA token (`converters={"a": float}` with a blank field) still raises here; the `python` engine retries with those rows masked. That is the other half of GH-13302, and the whatsnew and docstring claim only output-matching.\n- GH-13302\'s discussion favored applying `na_values` to the raw token *before* the converter. That is a semantics change for both engines and would need a deprecation; this PR only reconciles the engines, one of the open items on the GH-12686 tracker.\n\nNote `True == 1`, so a bool returned by a converter matches a numeric `na_values` entry. That is intentional: the same read without a converter, `Series.isin`, and the mask the `python` engine itself computes all agree.\n\nAI disclosure: drafted with Claude Code (`claude opus 5 (high)`), which wrote the fix, tests and docs and ran a c-vs-python differential across the converter/na_values input axes; reviewed by me.',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68689/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68689/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68688',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68688/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68688/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/68688/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/68688',
  'id': 5442780552,
  'node_id': 'PR_kwDOAA0YD88AAAABDXdCBg',
  'number': 68688,
  'title': "BUG: object-dtype astype to timedelta64 ignored the dtype's unit",
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None,
    'archived_at': None,
    'archived_by': None},
   {'id': 31404521,
    'node_id': 'MDU6TGFiZWwzMTQwNDUyMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dtype%20Conversions',
    'name': 'Dtype Conversions',
    'color': 'e102d8',
    'default': False,
    'description': 'Unexpected or buggy dtype conversions',
    'archived_at': None,
    'archived_by': None},
   {'id': 49597148,
    'node_id': 'MDU6TGFiZWw0OTU5NzE0OA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timedelta',
    'name': 'Timedelta',
    'color': '5319e7',
    'default': False,
    'description': 'Timedelta data type',
    'archived_at': None,
    'archived_by': None},
   {'id': 3555077089,
    'node_id': 'LA_kwDOAA0YD87T5ivh',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Astype',
    'name': 'Astype',
    'color': 'FD8B10',
    'default': False,
    'description': '',
    'archived_at': None,
    'archived_by': None}],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-09-13T21:04:14Z',
  'updated_at': '2026-09-13T21:04:30Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'MEMBER',
  'issue_field_values': [],
  'type': None,
  'active_lock_reason': None,
  'draft': True,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/68688',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/68688',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/68688.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/68688.patch',
   'merged_at': None},

In [56]:
# create a dataframe with fields (columns) of interests
df4 = pd.DataFrame(v1, columns=['number', 'title', 'labels', 'state'])

In [57]:
df4

,number,title,labels,state
0,68700,DEPR: warn on ambiguous .loc MultiIndex tuple ...,[],open
1,68699,BUG: preserve dtype for empty DataFrame min/ma...,[],open
2,68689,BUG: read_csv c engine ignored na_values on a ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
3,68688,BUG: object-dtype astype to timedelta64 ignore...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
4,68687,BUG: read_json/read_html reported every OSErro...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
...,...,...,...,...
25,68489,DOC: Self-host image in pandas 1.0 blog post,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
26,68486,ERR: Report dtype mismatch for NaT arrays with...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
27,68465,BUG: defer the blocked-numexpr warning to firs...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
28,68461,ENH: Implement positional results for future.p...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
29,68460,ENH: Implement Series.__getitem__ with future....,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open

In [ ]:
##Python Working with Data Part II

In [3]:
### filtering out missing data

# using dropna method
from numpy import nan as NA
series1 = pd.Series([1, NA, 3.5, NA, 7])

In [4]:
series1.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [5]:
# using notnull method and boolean indexing
series1[series1.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [6]:
df5 = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5,3.]])

In [7]:
# drop any row having NaN in a dataframe
# using dropna method
df5

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [8]:
df5.dropna()

     0    1    2
0  1.0  6.5  3.0

In [9]:
# drop rows where all elements are NAS
# using how argument
df5.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [10]:
# drop columns using axis=1
df5[3]=8
df5

     0    1    2  3
0  1.0  6.5  3.0  8
1  1.0  NaN  NaN  8
2  NaN  NaN  NaN  8
3  NaN  6.5  3.0  8

In [11]:
df5.dropna(axis=1)

   3
0  8
1  8
2  8
3  8

In [12]:
df5[4] = NA
df5

     0    1    2  3   4
0  1.0  6.5  3.0  8 NaN
1  1.0  NaN  NaN  8 NaN
2  NaN  NaN  NaN  8 NaN
3  NaN  6.5  3.0  8 NaN

In [13]:
df5.dropna(axis=1, how='all')

     0    1    2  3
0  1.0  6.5  3.0  8
1  1.0  NaN  NaN  8
2  NaN  NaN  NaN  8
3  NaN  6.5  3.0  8

In [14]:
# filter out rows with Less than a specified no. of columns without NA values
df6 = pd.DataFrame(np.random.randn(7, 3))
df6.iloc[:4, 1] = NA
df6.iloc[:2, 2] = NA
df6

          0         1         2
0  0.892066       NaN       NaN
1 -0.055024       NaN       NaN
2 -0.557615       NaN -1.796834
3 -0.725345       NaN  0.802587
4 -0.420214 -0.419087  0.362830
5 -2.229182 -0.357155  1.194951
6 -0.653197 -0.559566 -0.527734

In [15]:
# using thresh argument
df6.dropna(thresh=2)

          0         1         2
2 -0.557615       NaN -1.796834
3 -0.725345       NaN  0.802587
4 -0.420214 -0.419087  0.362830
5 -2.229182 -0.357155  1.194951
6 -0.653197 -0.559566 -0.527734

In [16]:
### filling in the missing data
# using fillna method
# e.g., replace NAs with 0s
df6.fillna(0)

          0         1         2
0  0.892066  0.000000  0.000000
1 -0.055024  0.000000  0.000000
2 -0.557615  0.000000 -1.796834
3 -0.725345  0.000000  0.802587
4 -0.420214 -0.419087  0.362830
5 -2.229182 -0.357155  1.194951
6 -0.653197 -0.559566 -0.527734

In [17]:
# e.g., replace as per a dict
# column 1: 0.5 and column2: 0
df6.fillna({1: 0.5,2:0})

          0         1         2
0  0.892066  0.500000  0.000000
1 -0.055024  0.500000  0.000000
2 -0.557615  0.500000 -1.796834
3 -0.725345  0.500000  0.802587
4 -0.420214 -0.419087  0.362830
5 -2.229182 -0.357155  1.194951
6 -0.653197 -0.559566 -0.527734

In [19]:
# in-place modifying the dataframe
# using the inplace argument
_ = df6.fillna(0, inplace=True)

In [20]:
df6

          0         1         2
0  0.892066  0.000000  0.000000
1 -0.055024  0.000000  0.000000
2 -0.557615  0.000000 -1.796834
3 -0.725345  0.000000  0.802587
4 -0.420214 -0.419087  0.362830
5 -2.229182 -0.357155  1.194951
6 -0.653197 -0.559566 -0.527734

In [21]:

# using interpolation methods such as ffill
df7 = pd.DataFrame(np.random.randn(6, 3))
df7.iloc[2:, 1] = NA
df7.iloc[4:, 2] = NA
df7

          0         1         2
0 -0.010527 -1.259181 -0.168633
1  0.882279  0.407816  1.983321
2 -0.327279       NaN -0.815746
3 -1.057319       NaN -1.538418
4  1.336517       NaN       NaN
5 -1.520383       NaN       NaN

In [22]:
df7.fillna(method='ffill')

C:\Users\bhavi\AppData\Local\Temp\ipykernel_28588\791972451.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df7.fillna(method='ffill')

          0         1         2
0 -0.010527 -1.259181 -0.168633
1  0.882279  0.407816  1.983321
2 -0.327279  0.407816 -0.815746
3 -1.057319  0.407816 -1.538418
4  1.336517  0.407816 -1.538418
5 -1.520383  0.407816 -1.538418

In [23]:
# limit the interpolation upto 2 times
df7.fillna(method='ffill', limit=2)

C:\Users\bhavi\AppData\Local\Temp\ipykernel_28588\1532784090.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df7.fillna(method='ffill', limit=2)

          0         1         2
0 -0.010527 -1.259181 -0.168633
1  0.882279  0.407816  1.983321
2 -0.327279  0.407816 -0.815746
3 -1.057319  0.407816 -1.538418
4  1.336517       NaN -1.538418
5 -1.520383       NaN -1.538418

In [24]:
# pass the mean or median value
df7.fillna(df7.mean())

          0         1         2
0 -0.010527 -1.259181 -0.168633
1  0.882279  0.407816  1.983321
2 -0.327279 -0.425682 -0.815746
3 -1.057319 -0.425682 -1.538418
4  1.336517 -0.425682 -0.134869
5 -1.520383 -0.425682 -0.134869

In [25]:
### removing duplicates
df8 = pd.DataFrame({'k1': ['one', 'two'] *3+ ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})
df8

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [26]:
# using duplicated method to find duplicate rows
df8.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [27]:
# dropping duplicate rows
# using drop_duplicates
df8.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [28]:
# dropping duplicate rows based on one particular columns instead of all the columns
df8['v1'] = range(7)

In [29]:
df8

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [30]:
# drop duplicate rows based on column k1
df8.drop_duplicates(['k1'])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [31]:
# keeping the last instance of duplicate rows instead of the first one (default)
# using keep argument
df8.drop_duplicates(['k1', 'k2'], keep='last')

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [32]:
df8.drop_duplicates(['k1', 'k2'])

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5

In [35]:


### perform transformations based on mappings

## data transfromations based on values
# e.g., mapping of each distinct agro food products to the agricultural crop
df9 = pd.DataFrame({'food': ['atta', 'maida', 'atta', 'sugar', 'gudh',
                             'atta', 'sugar', 'daliya', 'besan'],
                    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
df9

     food  ounces
0    atta     4.0
1   maida     3.0
2    atta    12.0
3   sugar     6.0
4    gudh     7.5
5    atta     8.0
6   sugar     3.0
7  daliya     5.0
8   besan     6.0

In [36]:
dict1 = {'atta': 'wheat',
         'maida': 'wheat',
         'sugar': 'sugarcane',
         'gudh': 'sugarcane',
         'daliya': 'wheat',
         'besan': 'chana dal'}

dict1

{'atta': 'wheat',
 'maida': 'wheat',
 'sugar': 'sugarcane',
 'gudh': 'sugarcane',
 'daliya': 'wheat',
 'besan': 'chana dal'}

In [37]:
# add a column in the dataframe to indicate the crop
# using map method to extract mapping from the dict object
df9['crop'] =df9['food'].map(dict1)
df9

     food  ounces       crop
0    atta     4.0      wheat
1   maida     3.0      wheat
2    atta    12.0      wheat
3   sugar     6.0  sugarcane
4    gudh     7.5  sugarcane
5    atta     8.0      wheat
6   sugar     3.0  sugarcane
7  daliya     5.0      wheat
8   besan     6.0  chana dal

In [38]:
## replacing values using replace method
series2 = pd.Series([1.,-999., 2.,-999.,-1000., 3.])
series2

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [39]:
# -999 values seem to be sentinel values for missing data
# replace these with NAs
series2.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [40]:
# replace multiple values
# e.g., -999, -1000
series2.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [41]:
# different replacement for each value
series2.replace([-999,-1000], [np.nan, -1])

0    1.0
1    NaN
2    2.0
3    NaN
4   -1.0
5    3.0
dtype: float64

In [42]:
series2.replace({-999: np.nan, -1000: -1})

0    1.0
1    NaN
2    2.0
3    NaN
4   -1.0
5    3.0
dtype: float64

In [43]:
## renaming index Labels
df10 = pd.DataFrame(np.arange(12).reshape((3, 4)), index=['Delhi', 'Mumbai', 'Banaglore'],
                    columns=['one', 'two', 'three', 'four'])

df10

           one  two  three  four
Delhi        0    1      2     3
Mumbai       4    5      6     7
Banaglore    8    9     10    11

In [44]:
f1 = lambda x: x[:3].upper()

In [45]:
# using map method of axis indexes
df10.index.map(f1)

Index(['DEL', 'MUM', 'BAN'], dtype='object')

In [46]:
df10.index=df10.index.map(f1)
df10

     one  two  three  four
DEL    0    1      2     3
MUM    4    5      6     7
BAN    8    9     10    11

In [47]:
# using rename method
df10

     one  two  three  four
DEL    0    1      2     3
MUM    4    5      6     7
BAN    8    9     10    11

In [48]:
df10.rename(index=str.title, columns=str.upper)

     ONE  TWO  THREE  FOUR
Del    0    1      2     3
Mum    4    5      6     7
Ban    8    9     10    11

In [49]:
# using dict mapping with rename method
df10

     one  two  three  four
DEL    0    1      2     3
MUM    4    5      6     7
BAN    8    9     10    11

In [50]:
df10.rename(index={'DEL': 'INDRAPRASTH'}, columns={'three': 'teen'})

             one  two  teen  four
INDRAPRASTH    0    1     2     3
MUM            4    5     6     7
BAN            8    9    10    11

In [51]:
# in-place modification using rename
# using inplace argument
df10

     one  two  three  four
DEL    0    1      2     3
MUM    4    5      6     7
BAN    8    9     10    11

In [53]:
df10.rename(index={'DEL': 'INDRAPRASTH'}, columns={'three': 'teen'}, inplace=True)

In [54]:
df10

             one  two  teen  four
INDRAPRASTH    0    1     2     3
MUM            4    5     6     7
BAN            8    9    10    11

In [55]:
##  Python Working with Data Part III

In [56]:
### binning of continuous variables
# e.g., age
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [57]:
# bin Lengths: 18-25, 26-35 etc.
# specify the bin edges
bins = [18, 25,35, 60, 100]

In [58]:
# create bin groups using cut function
age_grps = pd.cut(ages, bins)
age_grps

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [60]:
# numeric codes for all the cases
# using codes attribute
age_grps.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [61]:
# categories (bins) of age_grps variable
age_grps.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [62]:
# frequencies for different categories (bins) of age_grps
pd.value_counts(age_grps)

C:\Users\bhavi\AppData\Local\Temp\ipykernel_28588\2739763484.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_grps)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [63]:
# changing the open/close sides of the bin intervals
# default: left side is open and right side is closed
# using 'right' argument in the cut function
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [64]:
# changing bin names
# using labels argument
pd.cut(ages, bins, labels=['Youth', 'YoungAdult', 'MiddleAged', 'Senior'])

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [65]:
## no. of equal Length bins instead of specifying bin Lengths (bin edges)
# bin Length is based on min and max values
var2 = np.random.rand(20)

In [66]:
# e.g., 4 bins
pd.cut(var2, 4, precision=2)

[(0.48, 0.69], (0.48, 0.69], (0.48, 0.69], (0.048, 0.26], (0.048, 0.26], ..., (0.69, 0.91], (0.26, 0.48], (0.048, 0.26], (0.48, 0.69], (0.69, 0.91]]
Length: 20
Categories (4, interval[float64, right]): [(0.048, 0.26] < (0.26, 0.48] < (0.48, 0.69] < (0.69, 0.91]]

In [67]:
## bin Lengths based on sample quantiles
# roughly equal-Length bins
# using qcut function
var_grps = pd.qcut(var2, 4)
var_grps

[(0.618, 0.705], (0.618, 0.705], (0.238, 0.618], (0.0478, 0.238], (0.0478, 0.238], ..., (0.705, 0.908], (0.238, 0.618], (0.0478, 0.238], (0.618, 0.705], (0.705, 0.908]]
Length: 20
Categories (4, interval[float64, right]): [(0.0478, 0.238] < (0.238, 0.618] < (0.618, 0.705] < (0.705, 0.908]]

In [68]:
# frequencies for bins
pd.value_counts(var_grps)

C:\Users\bhavi\AppData\Local\Temp\ipykernel_28588\2351909932.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(var_grps)

(0.0478, 0.238]    5
(0.238, 0.618]     5
(0.618, 0.705]     5
(0.705, 0.908]     5
Name: count, dtype: int64

In [69]:
# specify quantiles
pd.qcut(var2, [0, 0.25, 0.5, 0.75, 1])

[(0.618, 0.705], (0.618, 0.705], (0.238, 0.618], (0.0478, 0.238], (0.0478, 0.238], ..., (0.705, 0.908], (0.238, 0.618], (0.0478, 0.238], (0.618, 0.705], (0.705, 0.908]]
Length: 20
Categories (4, interval[float64, right]): [(0.0478, 0.238] < (0.238, 0.618] < (0.618, 0.705] < (0.705, 0.908]]

In [70]:
### finding outliers

# Example:
df11 = pd.DataFrame(np.random.randn(1000, 4))

In [71]:
df11.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.016839     0.041083     0.014565    -0.022983
std       0.961411     0.987992     1.026218     0.981883
min      -2.982895    -3.019966    -3.077223    -3.160364
25%      -0.658310    -0.612872    -0.685259    -0.679147
50%      -0.052436     0.028468     0.008469    -0.026568
75%       0.621805     0.683099     0.748900     0.611881
max       2.753801     3.169094     2.866367     3.260280

In [72]:
# find values exceeding 3 or -3 for a particular column
# e.g., column 2 (third)
df11[2][np.abs(df11[2])>3]

448   -3.077223
Name: 2, dtype: float64

In [73]:
# find rows with values exceeding 3 or -3 in any column
df11[(np.abs(df11)>3).any(1)] #not worked since for older version

TypeError: DataFrame.any() takes 1 positional argument but 2 were given

In [74]:
df11[(np.abs(df11) > 3).any(axis=1)]

            0         1         2         3
286  0.507488  0.466482  0.193689 -3.160364
448 -0.039415 -0.374098 -3.077223 -1.080211
532  0.566167  3.037103 -1.279513 -0.180200
610 -0.192789  3.164809  1.293221  0.201417
690  1.429526  0.858255 -1.326620  3.260280
708  0.230797  3.153393  1.187666 -1.115918
734  0.741793  3.169094  0.609194 -0.482003
744  1.330385 -3.019966  1.444960  0.895716
792  0.927493  3.055595  1.461292  0.212187
840 -0.669438 -0.028339 -1.354648  3.116151
957  0.100099  0.347020 -1.002457 -3.152302

In [75]:
# modifying values outside a given range
# e.g., replace values outside the range -3 to 3 as -3 or 3
# use sign function to record the sign of values (1 or -1)
df11[(np.abs(df11)>3)]= np.sign(df11) * 3

In [76]:
df11.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.016839     0.040523     0.014643    -0.023046
std       0.961411     0.986147     1.025988     0.979705
min      -2.982895    -3.000000    -3.000000    -3.000000
25%      -0.658310    -0.612872    -0.685259    -0.679147
50%      -0.052436     0.028468     0.008469    -0.026568
75%       0.621805     0.683099     0.748900     0.611881
max       2.753801     3.000000     2.866367     3.000000

In [77]:
 ### random sampling and random reordering of rows

# Example:
df12 = pd.DataFrame(np.arange(5000*4).reshape((5000, 4)))
df12

          0      1      2      3
0         0      1      2      3
1         4      5      6      7
2         8      9     10     11
3        12     13     14     15
4        16     17     18     19
...     ...    ...    ...    ...
4995  19980  19981  19982  19983
4996  19984  19985  19986  19987
4997  19988  19989  19990  19991
4998  19992  19993  19994  19995
4999  19996  19997  19998  19999

[5000 rows x 4 columns]

In [78]:
# to randomly sample n rows without replacement
# using sample method
# e.g., 500 rows
df12.sample(n=500)

          0      1      2      3
4138  16552  16553  16554  16555
1269   5076   5077   5078   5079
696    2784   2785   2786   2787
4599  18396  18397  18398  18399
1341   5364   5365   5366   5367
...     ...    ...    ...    ...
605    2420   2421   2422   2423
362    1448   1449   1450   1451
1501   6004   6005   6006   6007
3333  13332  13333  13334  13335
1810   7240   7241   7242   7243

[500 rows x 4 columns]

In [79]:
# with replacement
# using replace argument
df12.sample(n=500, replace=True)

          0      1      2      3
2923  11692  11693  11694  11695
3501  14004  14005  14006  14007
4595  18380  18381  18382  18383
690    2760   2761   2762   2763
4642  18568  18569  18570  18571
...     ...    ...    ...    ...
1568   6272   6273   6274   6275
1040   4160   4161   4162   4163
2023   8092   8093   8094   8095
4962  19848  19849  19850  19851
939    3756   3757   3758   3759

[500 rows x 4 columns]

In [80]:
# random reordering of row indices
# using permutation function
df13 = pd.DataFrame(np.arange(5 *4).reshape((5, 4)))
df13

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [81]:
# output indicates the new order drawn randomly
permut = np.random.permutation(5)
permut

array([4, 3, 2, 0, 1], dtype=int32)

In [82]:
# reindexing using reindex method
df13.reindex(permut)

    0   1   2   3
4  16  17  18  19
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7

In [83]:
# reindexing using take method
df13.take(permut)

    0   1   2   3
4  16  17  18  19
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7

In [84]:
### dummy variables
# converting categorical variables into dummy variables

# dummy variables are filled with 1s (prsence of the category in a row or case)
# and 0s (absence of the category in a row or case)

# let's take a categorical variable with k distinct values (categories)
df14 = pd.DataFrame({'var': ['b', 'b', 'a', 'c', 'a', 'b']})
df14

  var
0   b
1   b
2   a
3   c
4   a
5   b

In [85]:
# using get_dummies function
# e.g. var has 3 distinct values: 'a', 'b', and 'c'
pd.get_dummies(df14['var'])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [86]:
pd.get_dummies(df14['var'], dtype=int)

   a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [88]:
# renaming the dummy variables
# using prefix argument
pd.get_dummies(df14['var'], prefix='var',dtype=int)

   var_a  var_b  var_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [89]:
# combining dummy creation and binning
# using a combination of get_dummies and cut functions
var3 = np.random.rand(10)

In [90]:
var3

array([0.72528041, 0.17618358, 0.8936957 , 0.42357138, 0.36311982,
       0.77732439, 0.45402765, 0.16046234, 0.75819418, 0.87113459])

In [91]:
bins1 = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [92]:
pd.cut(var3, bins1)

[(0.6, 0.8], (0.0, 0.2], (0.8, 1.0], (0.4, 0.6], (0.2, 0.4], (0.6, 0.8], (0.4, 0.6], (0.0, 0.2], (0.6, 0.8], (0.8, 1.0]]
Categories (5, interval[float64, right]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] < (0.8, 1.0]]

In [94]:
pd.get_dummies(pd.cut(var3, bins1),dtype=int)

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           1           0
1           1           0           0           0           0
2           0           0           0           0           1
3           0           0           1           0           0
4           0           1           0           0           0
5           0           0           0           1           0
6           0           0           1           0           0
7           1           0           0           0           0
8           0           0           0           1           0
9           0           0           0           0           1

In [95]:
### String and Text Processing Part I

In [96]:
### string and text processing ###

# Python is quite popular for its ease of use for text operations
# string object's built-in methods are sufficient for most text operations
# regular expressions can be used for complex pattern matching and text manipulations

# Example: creating terms from a comma-separated string
str1 = 'a, ab, abc, abcd, abcde'

In [97]:
str1

'a, ab, abc, abcd, abcde'

In [98]:
# create a list of terms using split method
str1.split(',')

['a', ' ab', ' abc', ' abcd', ' abcde']

In [99]:
# combine split with strip (to trim whitespace)
terms = [x.strip() for x in str1.split(',')]

In [100]:
terms

['a', 'ab', 'abc', 'abcd', 'abcde']

In [101]:
# Example: concatenation of strings with delimiters

# e.g., :: as a delimiter

# first approach:
# first segregate each term
first, second, third, fourth, fifth = terms

In [102]:
# using + operator for concatenation
first + ' :: ' + second + ' :: ' + third + ' :: ' + fourth + ' :: ' + fifth

'a :: ab :: abc :: abcd :: abcde'

In [103]:
# second approach:
# using join method
' :: '.join(terms)

'a :: ab :: abc :: abcd :: abcde'

In [104]:
# Example: checking presence of a term or finding its index in the string
str1

'a, ab, abc, abcd, abcde'

In [105]:
# using in keyword
'abcd' in str1

True

In [106]:
# using index method
str1.index('abcd')

12

In [107]:
str1.index('abcdef')

ValueError: substring not found

In [108]:
# using find method
str1.find('abcd')

12

In [109]:
str1.find('abcdef')

-1

In [110]:
# Example: counting the occurences of a term and replacing with a substitute
# using count method
str1.count('abc')

3

In [111]:
# using replace method
# e.g., replace ',' with ''
str1.replace(',','')

'a ab abc abcd abcde'

In [112]:
# # e.g., replace ',' with ':'
str1.replace(',', ':')

'a: ab: abc: abcd: abcde'

In [3]:
## regular expressions ##

# using Python's built-in re module
# three types of functions: pattern matching, substitution, and splitting
# a regex describes a pattern to locate in the text

# Execution mechanism:
# Ist approach: suitable when one or two texts or strings are to be processed using same regex
# for a given line of code involving regex to process a text,
# first regex is compiled internally then code is applied on the text

# IInd approach: suitable when many texts or strings are to be processed using same regex
# regex can be compiled and reused as a regex object

import re

In [4]:
# Example: split a string having different types of whitespace characters (tabs, spaces, and newlines)
# regex: '\s+'
text = "om namah\t shivay \tchant"

In [5]:
# Ist
# using split function
re.split('\s+', text)

['om', 'namah', 'shivay', 'chant']

In [9]:
## IInd
# using compile function
regex = re.compile('\s+')

In [10]:
regex.split(text)

['om', 'namah', 'shivay', 'chant']

In [11]:
# List of all patterns matching a regex
# using findall method
# returns all the matches
regex.findall(text)

[' ', '\t ', ' \t']

In [12]:
# Example: indetify email addresses from a text block
text1 = """Ramesh ramesh@iitr.ac.in
Mukesh mukesh@gmail.com
Rajib rajib@gmail.com
santosh santosh@yahoo.com"""

In [13]:
# regular expression to identify most email addresses
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [14]:
# compile the regex
regex1 = re.compile(pattern, flags=re. IGNORECASE)

In [15]:
# using finall method to produce all the email addresses
regex1.findall(text1)

['ramesh@iitr.ac.in',
 'mukesh@gmail.com',
 'rajib@gmail.com',
 'santosh@yahoo.com']

In [16]:
# using search method
# returns a match object with only the start and end position of the first match of the pattern in the string
m1 = regex1.search(text1)

In [17]:
# using start and end methods of the match object
text1[m1.start():m1.end()]

'ramesh@iitr.ac.in'

In [18]:
# using match method
# checks for matches only at the start of the string
regex1.match(text1)

In [19]:
print(regex1.match(text1))

None

In [20]:
# using sub method to find and replace all the occurences of the pattern with a substitute
regex1.sub('found', text1)

'Ramesh found\nMukesh found\nRajib found\nsantosh found'

In [21]:
print(regex1.sub('found', text1))

Ramesh found
Mukesh found
Rajib found
santosh found

In [22]:
# Example: find email addresses and segment each address into its three components:
# username, domain name, and domain suffix

# parentheses around the parts of the pattern to segment
pattern1 =r'([A-Z0-9._ %+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [23]:
# compile the regex
regex2 = re.compile(pattern1, flags=re.IGNORECASE)

In [24]:
# using findall to produce a list of tuples having the segregated components
regex2.findall(text1)

[('Ramesh ramesh', 'iitr.ac', 'in'),
 ('Mukesh mukesh', 'gmail', 'com'),
 ('Rajib rajib', 'gmail', 'com'),
 ('santosh santosh', 'yahoo', 'com')]

In [25]:
# using sub method to print segregated components
# addtional functionality of sub method: symbol-component mapping
# \1 refers to the first component, \2 refers to the second, and so forth

print(regex2.sub(r'Username: \1, Domain: \2, Suffix: \3', text1))

Username: Ramesh ramesh, Domain: iitr.ac, Suffix: in
Username: Mukesh mukesh, Domain: gmail, Suffix: com
Username: Rajib rajib, Domain: gmail, Suffix: com
Username: santosh santosh, Domain: yahoo, Suffix: com

In [26]:
## String and Text Processing Part II

In [27]:
 # Example: segregate pattern components
text2 = "ramesh@iitr.ac.in"

In [28]:
# using match method
# additional functionality of segmenting pattern components into groups
# returns a match object
m2 = regex2.match(text2)
m2

In [29]:
# using groups method of the match object
m2.groups()

('ramesh', 'iitr.ac', 'in')

In [33]:
## vectorized string operations ##
# string operations on series and dataframe objects

# Example: Let's create a series object of email addresses
dict2 = {'Ramesh': 'ramesh@iitr.ac.in', 'Mukesh': 'mukesh@gmail.com', 'Rajib': 'rajib@gmail.com', 'santosh': np.nan}

In [34]:
dict2

{'Ramesh': 'ramesh@iitr.ac.in',
 'Mukesh': 'mukesh@gmail.com',
 'Rajib': 'rajib@gmail.com',
 'santosh': nan}

In [35]:
series3 = pd.Series(dict2)

In [36]:
series3

Ramesh     ramesh@iitr.ac.in
Mukesh      mukesh@gmail.com
Rajib        rajib@gmail.com
santosh                  NaN
dtype: object

In [37]:
# using isnull method to find the missing values
series3.isnull()

Ramesh     False
Mukesh     False
Rajib      False
santosh     True
dtype: bool

In [38]:
# using str attribute of series objects to call methods related to string operations
# advantage: these methods skip NAs, while string and regular expression methods fail on NAS

# Example: check whether strings (email addresses) have a particular term
# using contains method
# returns boolean array
series3.str.contains('gmail')

Ramesh     False
Mukesh      True
Rajib       True
santosh      NaN
dtype: object

In [40]:
# using regex to segregate components of an email address
pattern2 ='([A-Z0-9._ %+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [42]:
# using findall to detect all pattern occurences in each string
series3.str.findall(pattern2, flags=re.IGNORECASE)

Ramesh     [(ramesh, iitr.ac, in)]
Mukesh      [(mukesh, gmail, com)]
Rajib        [(rajib, gmail, com)]
santosh                        NaN
dtype: object

In [43]:
# Example: vectorized element access

# using match method to find whether each string (email address) matches the pattern
series3.str.match(pattern2, flags=re.IGNORECASE)

Ramesh     True
Mukesh     True
Rajib      True
santosh     NaN
dtype: object

In [44]:
# accessing elements of the strings
# using get method
series3.str.get(0)

Ramesh       r
Mukesh       m
Rajib        r
santosh    NaN
dtype: object

In [45]:
series3.str.get(1)

Ramesh       a
Mukesh       u
Rajib        a
santosh    NaN
dtype: object

In [46]:
# accessing using index
series3.str[2]

Ramesh       m
Mukesh       k
Rajib        j
santosh    NaN
dtype: object

In [47]:
# Example: slicing strings
series3.str[:3]

Ramesh     ram
Mukesh     muk
Rajib      raj
santosh    NaN
dtype: object

In [48]:
## categorical type ##
# yield significant performance improvements for analytics
# used for holding data that uses the integer-based categorical representation

# binning functions cut and qcut functions return categorical objects

# Example: baskets of fruits
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)

df15 = pd.DataFrame({'fruit': fruits,
                     'basket_id': np.arange(N),
                     'count': np.random.randint(3, 15, size=N),
                     'weight': np.random.uniform(0, 4, size=N)},
                    columns=['basket_id', 'fruit', 'count', 'weight'])

df15

   basket_id   fruit  count    weight
0          0   apple     12  3.652478
1          1  orange      4  2.499790
2          2   apple     10  1.285238
3          3   apple      9  3.435452
4          4   apple     12  2.756367
5          5  orange      9  2.938138
6          6   apple      4  3.767345
7          7   apple     12  0.170914

In [49]:
# converting fruit column into categorical type
# using astype method
fruit_cat = df15['fruit'].astype('category')

In [50]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [51]:
# values attribute is a categorical object
cat1 = fruit_cat.values
cat1

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']
Categories (2, object): ['apple', 'orange']

In [52]:
type(cat1)

pandas.core.arrays.categorical.Categorical

In [53]:
# attributes of a categorical object: categories and codes
cat1.categories

Index(['apple', 'orange'], dtype='object')

In [54]:
cat1.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [55]:
# converting a dataframe column to categorical
df15['fruit'] = df15['fruit'].astype('category')

In [56]:
df15.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [57]:
## creating a categorical object from sequences
# using Categorical function
cat2 = pd.Categorical(['young', 'youngadult', 'midaged', 'young', 'youngadult'])

In [58]:
cat2

['young', 'youngadult', 'midaged', 'young', 'youngadult']
Categories (3, object): ['midaged', 'young', 'youngadult']

In [59]:
# creating a categorical object from separate sequences for categories and codes
# using Categorical.from_codes function
categories = ['C', 'B', 'A']
codes = [0, 1, 2, 0, 0, 1]
cat3 = pd.Categorical.from_codes(codes, categories)

In [60]:
cat3

['C', 'B', 'A', 'C', 'C', 'B']
Categories (3, object): ['C', 'B', 'A']

In [61]:
# creating a categorical object with specific ordering of the categories (an ordinal variable)
# using ordered argument
cat4 = pd.Categorical.from_codes(codes, categories, ordered=True)
cat4

['C', 'B', 'A', 'C', 'C', 'B']
Categories (3, object): ['C' < 'B' < 'A']

In [62]:
cat5 = pd.Categorical(['young', 'youngadult', 'midaged', 'young', 'youngadult'], ordered=True)

In [63]:
cat5

['young', 'youngadult', 'midaged', 'young', 'youngadult']
Categories (3, object): ['midaged' < 'young' < 'youngadult']

In [64]:
# converting an unordered categorical variable (nominal variable) into an ordered categorical variable (ordinal variable)
# using as_ordered method
cat2.as_ordered()

['young', 'youngadult', 'midaged', 'young', 'youngadult']
Categories (3, object): ['midaged' < 'young' < 'youngadult']

In [65]:
# categorical data need not be strings
# it can be any immutable value types
cat6 = pd.Categorical([-1, 0, 0, 1, -1])

In [66]:
cat6

[-1, 0, 0, 1, -1]
Categories (3, int64): [-1, 0, 1]

In [67]:
## categorical methods

# Example: setting or adding categories
# using set_categories method
cat3

['C', 'B', 'A', 'C', 'C', 'B']
Categories (3, object): ['C', 'B', 'A']

In [68]:
# add one more category
cat7 = cat3.set_categories(['A', 'B', 'c', 'D'])

In [69]:
cat7

[NaN, 'B', 'A', NaN, NaN, 'B']
Categories (4, object): ['A', 'B', 'c', 'D']

In [70]:
# using value_counts method
cat7.value_counts()

A    1
B    2
c    0
D    0
Name: count, dtype: int64

In [71]:
# trimming unobserved categories
# using remove_unused_categories method
cat7.remove_unused_categories()

[NaN, 'B', 'A', NaN, NaN, 'B']
Categories (2, object): ['A', 'B']

In [72]:
# creating dummy variables
# using get_dummies method
cat3

['C', 'B', 'A', 'C', 'C', 'B']
Categories (3, object): ['C', 'B', 'A']

In [73]:
pd.get_dummies(cat3, prefix='cat3')

   cat3_C  cat3_B  cat3_A
0    True   False   False
1   False    True   False
2   False   False    True
3    True   False   False
4    True   False   False
5   False    True   False

In [74]:
##### End of Session on Python Working with Data #####