In [13]:
### pandas package
# Used to work with heterogeneous (tabular) data
# Facilitates faster and easier data processing

import pandas as pd

In [14]:
# Frequently used libraries
from pandas import Series, DataFrame

In [15]:
## Data structures: Series and DataFrame

## Series
# A sequence of values (similar to 1darray) along with an explicit custom index to access the values
# Like a fixed-Length dict: a mapping of index values to data values
# created using Series function
series1 = pd.Series([22, 33, 44, 55]) # default index: 0 to n-1

In [16]:
series1

0    22
1    33
2    44
3    55
dtype: int64

In [17]:
# Series properties (attributes)
# 'values'
# it is an array object
series1.values

array([22, 33, 44, 55])

In [18]:
# 'index'
# it is like range(n)
series1.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
# custom index: as a list of labels
series2 = pd.Series([22, 33, 44, 55], index=['a', 'b', 'c', 'd'])

In [20]:
series2

a    22
b    33
c    44
d    55
dtype: int64

In [21]:
# check presence or abence of labels in a series
'c' in series2

True

In [22]:
'e' in series2

False

In [23]:
series2.values

array([22, 33, 44, 55])

In [24]:
series2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [25]:
# accessing values using labelled indices
series2['a']

np.int64(22)

In [26]:

series2[['a', 'c']]

a    22
c    44
dtype: int64

In [27]:

series2[['c', 'a']] #order was not important

c    44
a    22
dtype: int64

In [28]:
# index-value link is not disturbed by execution of various operations
# automatic alignment of index labels with corresponding values and results just like in 'R platform'
# filtering
series2[series2>0]

a    22
b    33
c    44
d    55
dtype: int64

In [29]:
# scalar multiplication
series2*9

a    198
b    297
c    396
d    495
dtype: int64

In [30]:
# math operation
import numpy as np
np.exp(series2)

a    3.584913e+09
b    2.146436e+14
c    1.285160e+19
d    7.694785e+23
dtype: float64

In [31]:
# converting Python dict object into a series object
PIN_code = {'Roorkee': 247667, 'Dehradun': 248001, 'Haridwar': 249401, 'Nainital': 263001}

In [32]:

series3 = pd.Series(PIN_code)

In [33]:

series3

Roorkee     247667
Dehradun    248001
Haridwar    249401
Nainital    263001
dtype: int64

In [34]:

series3.index

Index(['Roorkee', 'Dehradun', 'Haridwar', 'Nainital'], dtype='object')

In [35]:
# changing index using index argument
# e.g., order of indices
cities = ['Dehradun', 'Haridwar', 'Nainital', 'Roorkee', 'Tehri Garhwal']

In [36]:
series4 = pd.Series(PIN_code, index=cities)
series4

Dehradun         248001.0
Haridwar         249401.0
Nainital         263001.0
Roorkee          247667.0
Tehri Garhwal         NaN
dtype: float64

In [37]:
# detect missing data
# using isnull and not null functions
pd.isnull(series4)

Dehradun         False
Haridwar         False
Nainital         False
Roorkee          False
Tehri Garhwal     True
dtype: bool

In [38]:
pd.notnull(series4)

Dehradun          True
Haridwar          True
Nainital          True
Roorkee           True
Tehri Garhwal    False
dtype: bool

In [39]:
# alignment feature
series3 + series4

Dehradun         496002.0
Haridwar         498802.0
Nainital         526002.0
Roorkee          495334.0
Tehri Garhwal         NaN
dtype: float64

In [40]:
# 'name' attributes of series object and its index
series4.name = 'PIN_code'

In [41]:
series4.index.name = 'city'

In [42]:
series4

city
Dehradun         248001.0
Haridwar         249401.0
Nainital         263001.0
Roorkee          247667.0
Tehri Garhwal         NaN
Name: PIN_code, dtype: float64

In [43]:
# changing index using index attribute
# e.g., index values
series1

0    22
1    33
2    44
3    55
dtype: int64

In [44]:
series1.index = [1, 2, 3, 4]

In [45]:
series1

1    22
2    33
3    44
4    55
dtype: int64

In [46]:
## Dataframe
# represents physically two-dimensional data in a tabular format of rows and columns
# it is like a dict of series elements having a common (row) index

# it has both a row and column index:
# row index is similar to series index (default: 0 to n-1)

# column index is variables' names (by default sorted alphabetically)
# columns can be variables of different value types (numeric, string, boolean, etc.)

# created using DataFrame function

# Let's take year-wise metro population data
dict1 = {'metro': ['Delhi', 'Delhi', 'Delhi', 'Mumbai', 'Mumbai', 'Mumbai'],
         'year': [2011, 2012, 2013, 2011, 2012, 2013],
         'popcr': [1.67, 1.72, 1.77, 2.07, 2.11, 2.15]}

In [47]:
df = pd.DataFrame(dict1)

In [48]:
df

    metro  year  popcr
0   Delhi  2011   1.67
1   Delhi  2012   1.72
2   Delhi  2013   1.77
3  Mumbai  2011   2.07
4  Mumbai  2012   2.11
5  Mumbai  2013   2.15

In [49]:
# first five rows
df.head()

    metro  year  popcr
0   Delhi  2011   1.67
1   Delhi  2012   1.72
2   Delhi  2013   1.77
3  Mumbai  2011   2.07
4  Mumbai  2012   2.11

In [50]:
## Database Using Python Pandas Part II ##

In [51]:
# changing the column index using columns argument
pd.DataFrame(dict1, columns=['year', 'metro', 'popcr'])

   year   metro  popcr
0  2011   Delhi   1.67
1  2012   Delhi   1.72
2  2013   Delhi   1.77
3  2011  Mumbai   2.07
4  2012  Mumbai   2.11
5  2013  Mumbai   2.15

In [52]:
# changing the row index using index argument
df2 = pd.DataFrame(dict1, columns=['year', 'metro', 'popcr', 'area'], index=list(range(1, 7)))
df2

   year   metro  popcr area
1  2011   Delhi   1.67  NaN
2  2012   Delhi   1.72  NaN
3  2013   Delhi   1.77  NaN
4  2011  Mumbai   2.07  NaN
5  2012  Mumbai   2.11  NaN
6  2013  Mumbai   2.15  NaN

In [53]:
# column index
df2.columns

Index(['year', 'metro', 'popcr', 'area'], dtype='object')

In [54]:
# accessing column using dict key Like notation
df2['popcr']

1    1.67
2    1.72
3    1.77
4    2.07
5    2.11
6    2.15
Name: popcr, dtype: float64

In [55]:
# accessing column using attribute like notation
df2.year

1    2011
2    2012
3    2013
4    2011
5    2012
6    2013
Name: year, dtype: int64

In [56]:
df2.popcr

1    1.67
2    1.72
3    1.77
4    2.07
5    2.11
6    2.15
Name: popcr, dtype: float64

In [57]:
# selecting particular row indices along a column
df2['popcr'][1:4]

2    1.72
3    1.77
4    2.07
Name: popcr, dtype: float64

In [58]:
df2['popcr' ][:5]

1    1.67
2    1.72
3    1.77
4    2.07
5    2.11
Name: popcr, dtype: float64

In [59]:
df2['popcr'][:5]

1    1.67
2    1.72
3    1.77
4    2.07
5    2.11
Name: popcr, dtype: float64

In [60]:


df2['popcr' ] [ :- 3]

1    1.67
2    1.72
3    1.77
Name: popcr, dtype: float64

In [61]:


df2['popcr' ] [ : ]

1    1.67
2    1.72
3    1.77
4    2.07
5    2.11
6    2.15
Name: popcr, dtype: float64

In [62]:
# accessing row using 'Loc' attribute
df2.loc[1]

year      2011
metro    Delhi
popcr     1.67
area       NaN
Name: 1, dtype: object

In [63]:
df2.loc[4]

year       2011
metro    Mumbai
popcr      2.07
area        NaN
Name: 4, dtype: object

In [64]:
## Data Processing & transformation
# value assignment
# e.g., area column
df2['area'] = 6000

In [65]:
df2

   year   metro  popcr  area
1  2011   Delhi   1.67  6000
2  2012   Delhi   1.72  6000
3  2013   Delhi   1.77  6000
4  2011  Mumbai   2.07  6000
5  2012  Mumbai   2.11  6000
6  2013  Mumbai   2.15  6000

In [66]:
# populating values
# e.g., area column
df2['area'] = np.arange(6000, 6600, 100)

In [67]:
df2

   year   metro  popcr  area
1  2011   Delhi   1.67  6000
2  2012   Delhi   1.72  6100
3  2013   Delhi   1.77  6200
4  2011  Mumbai   2.07  6300
5  2012  Mumbai   2.11  6400
6  2013  Mumbai   2.15  6500

In [68]:
# using series to populate values
# unmatched indices would be treated as missing values
val = pd.Series([1.7, 1.9, 2.1], index=[2, 4, 6])
df2['popcr'] = val

In [69]:
df2

   year   metro  popcr  area
1  2011   Delhi    NaN  6000
2  2012   Delhi    1.7  6100
3  2013   Delhi    NaN  6200
4  2011  Mumbai    1.9  6300
5  2012  Mumbai    NaN  6400
6  2013  Mumbai    2.1  6500

In [70]:
# assigning values to a nonexisting column will also create that column
df2['northern'] = (df2.metro == 'Delhi')

In [71]:
df2

   year   metro  popcr  area  northern
1  2011   Delhi    NaN  6000      True
2  2012   Delhi    1.7  6100      True
3  2013   Delhi    NaN  6200      True
4  2011  Mumbai    1.9  6300     False
5  2012  Mumbai    NaN  6400     False
6  2013  Mumbai    2.1  6500     False

In [72]:
# removing a column
# using del keyword
del df2['northern' ]

In [73]:
df2.columns

Index(['year', 'metro', 'popcr', 'area'], dtype='object')

In [74]:
# using nested dict of dicts to create a dataframe
# outer dict keys are used as column indices and inner keys as row indices

dict2 = {'Delhi': {2011: 1.6, 2014: 1.9}, 'Mumbai': {2011: 1.9, 2012: 2.0, 2013: 2.1}}

In [75]:

# inner dict keys are combined and sorted to form the index
df3 = pd.DataFrame(dict2)

In [76]:
df3

      Delhi  Mumbai
2011    1.6     1.9
2014    1.9     NaN
2012    NaN     2.0
2013    NaN     2.1

In [77]:
# transposing a dataframe: swapping rows and columns
# using T attribute
df3.T

        2011  2014  2012  2013
Delhi    1.6   1.9   NaN   NaN
Mumbai   1.9   NaN   2.0   2.1

In [78]:
# using dict of series to create a dataframe
dict2 = {'Delhi': df3['Delhi'][ :- 1], 'Mumbai': df3['Mumbai'][:2]}

In [79]:
dict2

{'Delhi': 2011    1.6
 2014    1.9
 2012    NaN
 Name: Delhi, dtype: float64,
 'Mumbai': 2011    1.9
 2014    NaN
 Name: Mumbai, dtype: float64}

In [80]:
pd.DataFrame(dict2)

      Delhi  Mumbai
2011    1.6     1.9
2012    NaN     NaN
2014    1.9     NaN

In [81]:
## name attributes in dataframe
df3

      Delhi  Mumbai
2011    1.6     1.9
2014    1.9     NaN
2012    NaN     2.0
2013    NaN     2.1

In [82]:
# for row index
df3.index.name = 'year'

In [83]:
# for columns index
df3.columns.name = 'metro'

In [84]:
df3

metro  Delhi  Mumbai
year
2011     1.6     1.9
2014     1.9     NaN
2012     NaN     2.0
2013     NaN     2.1

In [85]:
## values attribute in dataframe
# e.g., when dataframe columns have same dtype
df3.values

array([[1.6, 1.9],
       [1.9, nan],
       [nan, 2. ],
       [nan, 2.1]])

In [86]:
# e.g., when dataframe columns have different dtypes
df2

   year   metro  popcr  area
1  2011   Delhi    NaN  6000
2  2012   Delhi    1.7  6100
3  2013   Delhi    NaN  6200
4  2011  Mumbai    1.9  6300
5  2012  Mumbai    NaN  6400
6  2013  Mumbai    2.1  6500

In [87]:
df2.values

array([[2011, 'Delhi', nan, 6000],
       [2012, 'Delhi', 1.7, 6100],
       [2013, 'Delhi', nan, 6200],
       [2011, 'Mumbai', 1.9, 6300],
       [2012, 'Mumbai', nan, 6400],
       [2013, 'Mumbai', 2.1, 6500]], dtype=object)

In [96]:
## more on 'index objects' in series and dataframe
# immutable array-Like objects
# Also store metadata other than axis Labels (index values)

# sequences of labels used while creating a series or dataframe are internally converted into index object
series5 = pd.Series(range(3), index=['a', 'b', 'c'])

In [97]:
series5.index

Index(['a', 'b', 'c'], dtype='object')

In [98]:
# subsetting
ind1 = series5.index
ind1[1:]

Index(['b', 'c'], dtype='object')

In [99]:
ind1[0:2]

Index(['a', 'b'], dtype='object')

In [100]:
# immutability
ind1[1] = 'd'

TypeError: Index does not support mutable operations

In [101]:
# creating index using Index function
ind2 = pd.Index(np.arange(3))

In [102]:
ind2

Index([0, 1, 2], dtype='int64')

In [103]:
series6 = pd.Series([1.5,-2.5,0], index=ind2)

In [104]:
series6

0    1.5
1   -2.5
2    0.0
dtype: float64

In [105]:
series6.index is ind2

True

In [106]:
# index obejcts display set like behavior
df3

metro  Delhi  Mumbai
year
2011     1.6     1.9
2014     1.9     NaN
2012     NaN     2.0
2013     NaN     2.1

In [107]:
df3.columns

Index(['Delhi', 'Mumbai'], dtype='object', name='metro')

In [108]:
'Mumbai' in df3.columns

True

In [109]:
2014 in df3.index

True

In [110]:
# however, index objects can have duplicate elements unlike sets
ind3 = pd. Index(['beta', 'alpha', 'beta', 'sigma'])

In [111]:
ind3

Index(['beta', 'alpha', 'beta', 'sigma'], dtype='object')

In [112]:
series7 = pd.Series([1.1, 1.2, 1.3, 1.4], index=ind3)

In [113]:
series7

beta     1.1
alpha    1.2
beta     1.3
sigma    1.4
dtype: float64

In [114]:
series7['beta']

beta    1.1
beta    1.3
dtype: float64

In [115]:
### Database Using Python Pandas Part III

In [116]:
## interaction mechanism with the data in a series or dataframe

# Example: reindexing
# using reindex method
series8 = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [117]:
series8

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [118]:
series9 = series8.reindex(['a', 'b', 'c', 'd', 'e'])

In [119]:
series9

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [120]:
# filling values when reindexing
# using ffill method
series10 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [121]:
series10

0      blue
2    purple
4    yellow
dtype: object

In [122]:
series11= series10.reindex(range(6), method='ffill')
series11

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [123]:
# reindexing with dataframe
df4 = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Delhi', 'Mumbai', 'Bangalore'])

In [124]:
df4

   Delhi  Mumbai  Bangalore
a      0       1          2
c      3       4          5
d      6       7          8

In [125]:
# reindexing rows index
df5 = df4.reindex(['a', 'b', 'c', 'd'])
df5

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
b    NaN     NaN        NaN
c    3.0     4.0        5.0
d    6.0     7.0        8.0

In [126]:
# reindexing columns index
# using columns argument
df5.reindex(columns=['Bangalore', 'Delhi', 'Mumbai'])

   Bangalore  Delhi  Mumbai
a        2.0    0.0     1.0
b        NaN    NaN     NaN
c        5.0    3.0     4.0
d        8.0    6.0     7.0

In [127]:
# reindexing using loc attribute
df4.loc[['a', 'b', 'c', 'd'], ['Bangalore', 'Delhi', 'Mumbai']]
# in my version not worked ,

KeyError: "['b'] not in index"

In [ ]:
df5.reindex(index=['a', 'b', 'c', 'd'], columns=['Bangalore', 'Delhi', 'Mumbai'])

In [ ]:
# Example: dropping cases or rows
# using drop method
df5

In [128]:
df5.drop('b')

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
c    3.0     4.0        5.0
d    6.0     7.0        8.0

In [129]:
df5.drop(['a', 'c'])

   Delhi  Mumbai  Bangalore
b    NaN     NaN        NaN
d    6.0     7.0        8.0

In [130]:
# Example: dropping columns or variables
df5

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
b    NaN     NaN        NaN
c    3.0     4.0        5.0
d    6.0     7.0        8.0

In [131]:
df5.drop('Bangalore', axis=1) #drop column

   Delhi  Mumbai
a    0.0     1.0
b    NaN     NaN
c    3.0     4.0
d    6.0     7.0

In [132]:
df5.drop(['Delhi','Mumbai'], axis=1)

   Bangalore
a        2.0
b        NaN
c        5.0
d        8.0

In [133]:
# using in-place version of drop method
# using implace argument
df5

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
b    NaN     NaN        NaN
c    3.0     4.0        5.0
d    6.0     7.0        8.0

In [134]:
df5.drop('b', inplace=True)
df5

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
c    3.0     4.0        5.0
d    6.0     7.0        8.0

In [135]:
# Example: access, selection, and filtering

# working with a series
series11

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [136]:
series7

beta     1.1
alpha    1.2
beta     1.3
sigma    1.4
dtype: float64

In [137]:
# accessing one row
series11[3]

'purple'

In [138]:
series7['sigma']

np.float64(1.4)

In [139]:
# accessing a range of rows
series11[3:5]

3    purple
4    yellow
dtype: object

In [140]:
# selecting few rows
series7[['sigma', 'alpha']]

sigma    1.4
alpha    1.2
dtype: float64

In [141]:
series11[[1,5]]

1      blue
5    yellow
dtype: object

In [142]:
# filtering rows based on some logic
series7[series7<1.3]

beta     1.1
alpha    1.2
dtype: float64

In [143]:
# slicing

# Note: end-point in inclusive

series7['alpha': 'sigma']

alpha    1.2
beta     1.3
sigma    1.4
dtype: float64

In [144]:
# doesn't work with non-unique index Labels
series7['beta': 'sigma']

KeyError: "Cannot get left slice bound for non-unique label: 'beta'"

In [ ]:
series7['alpha':'sigma' ] = 1.3

In [ ]:
series7

In [ ]:
# working with a dataframe
df5

In [ ]:
# accessing columns
df5['Delhi']

In [ ]:
df5[['Delhi', 'Bangalore' ]]

In [ ]:
# slicing rows
df5[:2]

In [ ]:
df5[1:2]

In [ ]:
# filtering rows
df5[df5['Bangalore']>6]

In [ ]:
# working with a boolean dataframe
df5 < 5

In [145]:
df5[df5<5]

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
c    3.0     4.0        NaN
d    NaN     NaN        NaN

In [146]:
df5[df5<5] = 0

In [147]:
df5

   Delhi  Mumbai  Bangalore
a    0.0     0.0        0.0
c    0.0     0.0        5.0
d    6.0     7.0        8.0

In [148]:
## indexing operators loc and iloc
# Loc is used with axis labels
# iloc is used with integer values corresponding to axis labels
df5

   Delhi  Mumbai  Bangalore
a    0.0     0.0        0.0
c    0.0     0.0        5.0
d    6.0     7.0        8.0

In [149]:
df5.loc['a', 'Delhi']

np.float64(0.0)

In [150]:
df5.loc['a',['Delhi', 'Bangalore' ]]

Delhi        0.0
Bangalore    0.0
Name: a, dtype: float64

In [151]:
df5.loc[['a', 'b'], ['Delhi', 'Bangalore']]

KeyError: "['b'] not in index"

In [152]:
df5.reindex(index=['a', 'b'], columns=['Delhi', 'Bangalore'])

   Delhi  Bangalore
a    0.0        0.0
b    NaN        NaN

In [153]:
df5.iloc[0, 0] # first is for row , second is for column

np.float64(0.0)

In [154]:
df5.iloc[0, [0,1]]

Delhi     0.0
Mumbai    0.0
Name: a, dtype: float64

In [155]:
df5.iloc[[0,1], [0,1]]

   Delhi  Mumbai
a    0.0     0.0
c    0.0     0.0

In [156]:
df5.iloc[1] # second row

Delhi        0.0
Mumbai       0.0
Bangalore    5.0
Name: c, dtype: float64

In [157]:
df5.iloc[[1, 2], [2, 0,1]]

   Bangalore  Delhi  Mumbai
c        5.0    0.0     0.0
d        8.0    6.0     7.0

In [158]:
# slicing with Loc and iloc
df5. loc[:'c', 'Delhi']

a    0.0
c    0.0
Name: Delhi, dtype: float64

In [159]:
df5. loc['c':'d', 'Delhi']

c    0.0
d    6.0
Name: Delhi, dtype: float64

In [160]:
df5.loc['c':'d', 'Delhi': 'Bangalore']

   Delhi  Mumbai  Bangalore
c    0.0     0.0        5.0
d    6.0     7.0        8.0

In [161]:
df5.iloc[:, 1:2]

   Mumbai
a     0.0
c     0.0
d     7.0

In [162]:
df5.iloc[:, 0:2][df5.Mumbai != 0]

   Delhi  Mumbai
d    6.0     7.0

In [163]:
## more on integer indexing
series11

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [164]:
# fails due to inference ambiguity (label-based indexing or position-based)
series11[-3]

KeyError: -3

In [165]:
series7

beta     1.1
alpha    1.2
beta     1.3
sigma    1.4
dtype: float64

In [166]:
# succeeds due to inference ambiguity (label-based indexing or position-based)
series7[-1]

C:\Users\bhavi\AppData\Local\Temp\ipykernel_11048\3697122915.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series7[-1]

np.float64(1.4)

In [167]:
## Database Using Python Pandas Part IV

In [168]:
## Example: arithmetic between objects with unmatched indexes
# for matched indices, operation would be applied,
# for unmatched indices, a union of unmatched indices with NaN values is kept

series12 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [169]:
series12

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [170]:
series13 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [171]:
series13

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [172]:
series12 + series13

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [173]:
df5

   Delhi  Mumbai  Bangalore
a    0.0     0.0        0.0
c    0.0     0.0        5.0
d    6.0     7.0        8.0

In [174]:
df4

   Delhi  Mumbai  Bangalore
a      0       1          2
c      3       4          5
d      6       7          8

In [175]:
df4 = df4.reindex(['a', 'b', 'c', 'd'])

In [176]:
df4

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
b    NaN     NaN        NaN
c    3.0     4.0        5.0
d    6.0     7.0        8.0

In [177]:
df4+df5

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
b    NaN     NaN        NaN
c    3.0     4.0       10.0
d   12.0    14.0       16.0

In [178]:
# filling values in the operation involving unmacthed indices
# using add method

# fill NaNs in df5 with 0s
df4.add(df5, fill_value=0) # doesn't work since df4 still has NaN values

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
b    NaN     NaN        NaN
c    3.0     4.0       10.0
d   12.0    14.0       16.0

In [179]:
df4[1:2]=2
df4

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
b    2.0     2.0        2.0
c    3.0     4.0        5.0
d    6.0     7.0        8.0

In [180]:
df4.add(df5, fill_value=0)

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
b    2.0     2.0        2.0
c    3.0     4.0       10.0
d   12.0    14.0       16.0

In [181]:
2/df4

      Delhi    Mumbai  Bangalore
a       inf  2.000000       1.00
b  1.000000  1.000000       1.00
c  0.666667  0.500000       0.40
d  0.333333  0.285714       0.25

In [182]:
# using div method
df4.div(2)

   Delhi  Mumbai  Bangalore
a    0.0     0.5        1.0
b    1.0     1.0        1.0
c    1.5     2.0        2.5
d    3.0     3.5        4.0

In [183]:
# rdiv method: div with arguments flipped
df4.rdiv(2)

      Delhi    Mumbai  Bangalore
a       inf  2.000000       1.00
b  1.000000  1.000000       1.00
c  0.666667  0.500000       0.40
d  0.333333  0.285714       0.25

In [184]:
## Example: arithmetic between dataFrame and series

# similar to 2darray and 1darray scenario
# Let's first consider 2darray and 1darray
arr = np.arange(12.).reshape((3, 4))

In [185]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [186]:
arr.shape

(3, 4)

In [187]:
arr[0]

array([0., 1., 2., 3.])

In [188]:
arr[0].shape

(4,)

In [189]:
# difference between 2darray and 1darray
# "broadcasting" happens: subtraction is performed once for each row
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [190]:
df4

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
b    2.0     2.0        2.0
c    3.0     4.0        5.0
d    6.0     7.0        8.0

In [191]:
series0_df4 = df4.iloc[0]

In [192]:
series0_df4

Delhi        0.0
Mumbai       1.0
Bangalore    2.0
Name: a, dtype: float64

In [193]:
# broadcasting over the rows
df4 - series0_df4

   Delhi  Mumbai  Bangalore
a    0.0     0.0        0.0
b    2.0     1.0        0.0
c    3.0     3.0        3.0
d    6.0     6.0        6.0

In [194]:
# for unmatched indices, a union of unmatched indices with NaN values is kept
series14 = pd.Series(range(3), index=['Delhi', 'Hyderabad', 'Bangalore'])

In [195]:
series14

Delhi        0
Hyderabad    1
Bangalore    2
dtype: int64

In [196]:
df4 + series14

   Bangalore  Delhi  Hyderabad  Mumbai
a        4.0    0.0        NaN     NaN
b        4.0    2.0        NaN     NaN
c        7.0    3.0        NaN     NaN
d       10.0    6.0        NaN     NaN

In [197]:
# broadcast over the columns
# using various arithematic methods
# e.g., sub method for subtraction: match index axis and broadcast over cloumns
series15 = df4['Mumbai']

In [198]:
series15

a    1.0
b    2.0
c    4.0
d    7.0
Name: Mumbai, dtype: float64

In [199]:
df4

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
b    2.0     2.0        2.0
c    3.0     4.0        5.0
d    6.0     7.0        8.0

In [200]:
df4.sub(series15, axis='index')

   Delhi  Mumbai  Bangalore
a   -1.0     0.0        1.0
b    0.0     0.0        0.0
c   -1.0     0.0        1.0
d   -1.0     0.0        1.0

In [201]:
## Example: applying functions and methods

# numpy element-wise array functions
df4

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
b    2.0     2.0        2.0
c    3.0     4.0        5.0
d    6.0     7.0        8.0

In [202]:
# absolute value of each element in the dataframe
np.abs(df4)

   Delhi  Mumbai  Bangalore
a    0.0     1.0        2.0
b    2.0     2.0        2.0
c    3.0     4.0        5.0
d    6.0     7.0        8.0

In [203]:
# dataframe methods

# apply method: used to apply a funtion on all columns or rows (1darrays)
# e.g., difference between max and min value of a series
f = lambda x: x.max() -x.min()

In [204]:
# broadcast over the columns
df4.apply(f)

Delhi        6.0
Mumbai       6.0
Bangalore    6.0
dtype: float64

In [205]:
# broadcast over the rows
df4.apply(f, axis='columns')

a    2.0
b    0.0
c    2.0
d    2.0
dtype: float64

In [206]:
# sum method
df4.sum() # column sums

Delhi        11.0
Mumbai       14.0
Bangalore    17.0
dtype: float64

In [207]:
df4.sum(axis='columns') # row sums

a     3.0
b     6.0
c    12.0
d    21.0
dtype: float64

In [208]:
# mean method
df4.mean() # column means

Delhi        2.75
Mumbai       3.50
Bangalore    4.25
dtype: float64

In [209]:
df4.mean(axis='columns') # row means

a    1.0
b    2.0
c    4.0
d    7.0
dtype: float64

In [210]:
# returning multiple values using series
def f1(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [211]:
df4.apply(f1)

     Delhi  Mumbai  Bangalore
min    0.0     1.0        2.0
max    6.0     7.0        8.0

In [212]:
# element-wise Python methods

# e.g., compute a formatted string from each floating-point value
# using applymap method
f2 = lambda x: '%.2f' % x
df4.applymap(f2)

C:\Users\bhavi\AppData\Local\Temp\ipykernel_11048\2623547799.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df4.applymap(f2)

  Delhi Mumbai Bangalore
a  0.00   1.00      2.00
b  2.00   2.00      2.00
c  3.00   4.00      5.00
d  6.00   7.00      8.00

In [213]:
# using map method for series
df4['Delhi'].map(f2)

a    0.00
b    2.00
c    3.00
d    6.00
Name: Delhi, dtype: object

In [214]:
# sorting by index using sort_index method (default: ascending order)
series16 = pd.Series([4, 7, -3, 2], index=['d', 'a', 'b', 'c'])

In [215]:
series16

d    4
a    7
b   -3
c    2
dtype: int64

In [216]:
series16.sort_index()

a    7
b   -3
c    2
d    4
dtype: int64

In [217]:
df6 = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])
df6

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [218]:
# sorting the row index column
df6.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [219]:
# sorting the column index row
df6.sort_index(axis=1)

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [220]:
df6.sort_index(axis=1, ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [221]:
# sorting by values using sort_values method (NaN values at end)
series16.sort_values()

b   -3
c    2
d    4
a    7
dtype: int64

In [222]:
df7 = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [223]:
df7

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [224]:
# using one column
df7.sort_values(by='b')

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [225]:
# using multiple columns
df7.sort_values(by=['a','b'])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [226]:
# ranking by value using rank method (default: ascending order)
# default: breaks ties by assigning each group the mean rank
series17 = pd.Series([7, -5, 7, 4, 2, 0, 4])
series17

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [227]:
series17.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [228]:
# break ties using order of listing
# use method argument
# e.g., to break ties element listed first would be rated first
series17.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [229]:
series17.rank(method='first', ascending=False)

0    1.0
1    7.0
2    2.0
3    3.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [230]:
df7

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [231]:
# along the column by comparing row elements
df7.rank()

     b    a
0  3.0  1.5
1  4.0  3.5
2  1.0  1.5
3  2.0  3.5

In [232]:
# along the row by comparing column elements
df7.rank(axis='columns')

     b    a
0  2.0  1.0
1  2.0  1.0
2  1.0  2.0
3  2.0  1.0

In [233]:
## Example: axes with duplicate Labels
# many pandas functions require unique axis labels, but not all
series7

beta     1.1
alpha    1.2
beta     1.3
sigma    1.4
dtype: float64

In [234]:
# checking uniqueness of labels
# using 'is_unique' property of indexes
series7.index.is_unique

False

In [235]:
# changes in accessing elements using non-unique indexes
series7['alpha' ] # a scalar value is returned

np.float64(1.2)

In [236]:
series7['beta' ] # a series is returned

beta    1.1
beta    1.3
dtype: float64

In [237]:
df8 = pd.DataFrame(np.random.randn(5, 3), index=['a', 'a', 'b', 'b', 'c'])
df8

          0         1         2
a -0.920110 -0.182780 -1.128762
a  1.358683 -0.559661 -0.139003
b  1.064962  1.469818  0.329632
b  0.406000  0.535447 -0.082187
c -0.714827 -0.497929 -0.623526

In [238]:
df8.loc['b'] # a dataframe is returned

          0         1         2
b  1.064962  1.469818  0.329632
b  0.406000  0.535447 -0.082187

In [239]:
df8.loc['c'] # a series is returned

0   -0.714827
1   -0.497929
2   -0.623526
Name: c, dtype: float64

In [240]:
### Descriptive Statistics
##
df9 = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
                   index=['a', 'b', 'c', 'd'], columns=['one', 'two' ])

In [241]:
df9

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [242]:
# column sums
df9.sum() # NaN values are excluded

one    9.25
two   -5.80
dtype: float64

In [243]:
# row sums
df9.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [244]:
# skipna argument (default is True)
df9.sum(axis='columns', skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [245]:
# column means
df9.mean()

one    3.083333
two   -2.900000
dtype: float64

In [246]:
# column and row indexes of the maximum value
df9.idxmax()

one    b
two    d
dtype: object

In [247]:
df9

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [248]:
df9.idxmin()

one    d
two    b
dtype: object

In [249]:
# column cumulative sums
df9.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [250]:
# generating multiple statistics using describe method
df9.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [251]:
# describe method for non-numeric data
pd.Series(['a', 'a', 'b', 'c'] * 4).describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [252]:
pd.Series(['a', 'a', 'b', 'c'] * 4)

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [253]:
!pip install pandas-datareader

Requirement already satisfied: pandas-datareader in c:\users\bhavi\anaconda3\lib\site-packages (0.11.1)
Requirement already satisfied: lxml in c:\users\bhavi\anaconda3\lib\site-packages (from pandas-datareader) (5.3.0)
Requirement already satisfied: pandas>=2.1.4 in c:\users\bhavi\anaconda3\lib\site-packages (from pandas-datareader) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in c:\users\bhavi\anaconda3\lib\site-packages (from pandas-datareader) (2.32.5)
Requirement already satisfied: setuptools in c:\users\bhavi\anaconda3\lib\site-packages (from pandas-datareader) (80.9.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\bhavi\anaconda3\lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bhavi\anaconda3\lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\bhavi\anaconda3\lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\bhavi\anaconda3\lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\bhavi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.1.4->pandas-datareader) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\bhavi\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\bhavi\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\bhavi\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\bhavi\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2025.11.12)

In [254]:
## correlation and covariance
# computed from a pair of variables

# Example: obtain stock prices and volumes data from Yahoo! Finance
# using pandas_datareader module

# install pandas-datareader using anaconda navigator
# or using anaconda prompt: conda install pandas-datareader
# then
import pandas_datareader as web # not worked in newer version

In [255]:
import pandas_datareader.data as web

In [256]:
!pip install yfinance

Requirement already satisfied: yfinance in c:\users\bhavi\anaconda3\lib\site-packages (1.7.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\bhavi\anaconda3\lib\site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.15 in c:\users\bhavi\anaconda3\lib\site-packages (from yfinance) (0.16.3)
Requirement already satisfied: lxml>=4.9.0 in c:\users\bhavi\anaconda3\lib\site-packages (from yfinance) (5.3.0)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\bhavi\anaconda3\lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: numpy>=1.16.5 in c:\users\bhavi\anaconda3\lib\site-packages (from yfinance) (2.3.5)
Requirement already satisfied: pandas>=1.3.0 in c:\users\bhavi\anaconda3\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: peewee>=3.16.2 in c:\users\bhavi\anaconda3\lib\site-packages (from yfinance) (4.5.1)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\bhavi\anaconda3\lib\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\bhavi\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: pytz>=2022.5 in c:\users\bhavi\anaconda3\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: requests>=2.31 in c:\users\bhavi\anaconda3\lib\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: websockets>=13.0 in c:\users\bhavi\anaconda3\lib\site-packages (from yfinance) (17.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\bhavi\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\bhavi\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\bhavi\anaconda3\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\bhavi\anaconda3\lib\site-packages (from curl_cffi>=0.15->yfinance) (2025.11.12)
Requirement already satisfied: pycparser in c:\users\bhavi\anaconda3\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bhavi\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\bhavi\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\bhavi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\bhavi\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\bhavi\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\bhavi\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.5.0)

In [257]:
import yfinance as yf

In [258]:
# download the ticker level data
# using get_data_yahoo function
dataset = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']} # not worked in newer version

AttributeError: module 'pandas_datareader.data' has no attribute 'get_data_yahoo'

In [261]:
import yfinance as yf

dataset = {
    ticker: yf.download(
        ticker,
        start='2010-01-01',
        end='2020-01-01',
        auto_adjust=False,
        multi_level_index=False
    )
    for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']
}

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [260]:
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in dataset.items()})# not worked in newer version

KeyError: 'Adj Close'

In [262]:
price = pd.DataFrame({
    ticker: data['Adj Close']
    for ticker, data in dataset.items()
})

In [263]:
price.head()

                AAPL        IBM       MSFT       GOOG
Date
2010-01-04  6.400959  71.426460  22.984238  15.463772
2010-01-05  6.412026  70.563629  22.991665  15.395674
2010-01-06  6.310034  70.105255  22.850567  15.007570
2010-01-07  6.298368  69.862595  22.612926  14.658199
2010-01-08  6.340245  70.563629  22.768881  14.853610

In [264]:
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in dataset.items()})

In [265]:
volume.head()

                 AAPL      IBM      MSFT       GOOG
Date
2010-01-04  493729600  6438444  38409100   78541293
2010-01-05  601904800  7156104  49749600  120638494
2010-01-06  552160000  5863144  58182400  159744526
2010-01-07  477131200  6109268  50559700  257533695
2010-01-08  447610800  4390271  51197400  189680313

In [266]:
# percent changes of the prices
returns = price.pct_change()

In [267]:
# Last (most recent) 5 cases
returns.tail()

                AAPL       IBM      MSFT      GOOG
Date
2019-12-24  0.000951 -0.004205 -0.000191 -0.003914
2019-12-26  0.019840 -0.000518  0.008197  0.012534
2019-12-27 -0.000379  0.002668  0.001828 -0.006255
2019-12-30  0.005935 -0.018186 -0.008619 -0.011651
2019-12-31  0.007307  0.009261  0.000698  0.000659

In [268]:
# compute the correlations
# using corr method
# between two columns
returns['MSFT'].corr(returns[ 'IBM' ])

np.float64(0.49053645316726907)

In [269]:
returns['MSFT'].cov(returns[ 'IBM' ])

np.float64(8.658244550730094e-05)

In [270]:
# using column name as attribute
returns.MSFT.corr(returns. IBM)

np.float64(0.49053645316726907)

In [271]:
# using column name as attribute
returns.MSFT.corr(returns. IBM)

np.float64(0.49053645316726907)

In [272]:
# correlation matrix
returns.corr()

          AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.384224  0.457249  0.464215
IBM   0.384224  1.000000  0.490536  0.406393
MSFT  0.457249  0.490536  1.000000  0.540877
GOOG  0.464215  0.406393  0.540877  1.000000

In [273]:
# compute the covariances
# covariance matrix
returns.cov()

          AAPL       IBM      MSFT      GOOG
AAPL  0.000263  0.000077  0.000106  0.000116
IBM   0.000077  0.000152  0.000087  0.000077
MSFT  0.000106  0.000087  0.000205  0.000119
GOOG  0.000116  0.000077  0.000119  0.000237

In [274]:
# pairwise correlations with one particular column
# using corrwith method
returns.corrwith(returns. IBM)

AAPL    0.384224
IBM     1.000000
MSFT    0.490536
GOOG    0.406393
dtype: float64

In [275]:
# correlations between columns of different dataframes having same column names
returns.corrwith(volume)

AAPL   -0.066954
IBM    -0.156681
MSFT   -0.090116
GOOG   -0.019733
dtype: float64

In [276]:
# unique values using unique method
series18 = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [277]:
unq = series18.unique()
unq

array(['c', 'a', 'd', 'b'], dtype=object)

In [278]:
unq.sort()
unq

array(['a', 'b', 'c', 'd'], dtype=object)

In [279]:
# containing value frequencies using value_counts method
series18.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [280]:
# using pandas value_counts function
pd.value_counts(series18.values, sort=False)

C:\Users\bhavi\AppData\Local\Temp\ipykernel_11048\396298382.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(series18.values, sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [281]:
# filter presence or absence of an element
# using isin method
series18.isin(['b'])

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7    False
8    False
dtype: bool

In [282]:
series18.isin(['b', 'c'])

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [283]:
filter1 = series18.isin(['b', 'c'])
series18[filter1]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [284]:
# compute frequencies in multiple related columns
df10 = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4], 'Qu2': [2, 3, 1, 2, 3], 'Qu3': [1, 5, 2, 4, 4]})

In [285]:
df10

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [286]:
# row Labels indicate the distinct values of the dataframe
# values indicate the count of these distict values in the respective columns
df10.apply(pd.value_counts)

C:\Users\bhavi\AppData\Local\Temp\ipykernel_11048\1187321378.py:3: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df10.apply(pd.value_counts)

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [288]:
# fill NaN with 0s
df10.apply(pd.value_counts).fillna(0)

C:\Users\bhavi\AppData\Local\Temp\ipykernel_11048\2771157025.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df10.apply(pd.value_counts).fillna(0)

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [289]:
##### End of Session on Python pandas #####